version: "3.9"
services:
  mongo:
    image: mongo:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - ententia

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ententia-backend:1.0.0
    env_file:
      - .env
    volumes:
      - ${PWD}/backend:/home/ententia/code
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    networks:
      - ententia

  frontend:
    build:
      context: ./frontend/vite-project
      dockerfile: Dockerfile
    image: ententia-frontend:1.0.0
    ports:
      - "3000:80"
    networks:
      - ententia
    depends_on:
      - backend

networks:
  ententia:
    driver: bridge

volumes:
  mongo_data:
